const quizArr = [
  {
    id: 1,
    question: "यदि sin θ = 1/2 हो, तो θ का मान क्या हो सकता है?",
    options: {
      A: "0°",
      B: "30°",
      C: "45°",
      D: "60°",
    },
    answer: "B",
  },
  {
    id: 2,
    question: "cos 0° का मान क्या है?",
    options: {
      A: "0",
      B: "1",
      C: "-1",
      D: "1/2",
    },
    answer: "B",
  },
  {
    id: 3,
    question: "tan 45° का मान क्या है?",
    options: {
      A: "0",
      B: "1",
      C: "√3",
      D: "1/√3",
    },
    answer: "B",
  },
  {
    id: 4,
    question: "cosec 30° का मान क्या है?",
    options: {
      A: "2",
      B: "1",
      C: "√3",
      D: "1/2",
    },
    answer: "A",
  },
  {
    id: 5,
    question: "यदि θ एक तीव्र कोण है और sin θ = 3/5 है, तो cos θ का मान क्या होगा?",
    options: {
      A: "4/5",
      B: "3/5",
      C: "5/3",
      D: "1/5",
    },
    answer: "A",
  },
  {
    id: 6,
    question: "sin² θ + cos² θ का मान हमेशा क्या होगा?",
    options: {
      A: "1",
      B: "0",
      C: "2",
      D: "√2",
    },
    answer: "A",
  },
  {
    id: 7,
    question: "tan θ = sin θ / cos θ होता है। यह कथन:",
    options: {
      A: "सही",
      B: "गलत",
      C: "आंशिक रूप से सही",
      D: "निर्धारित नहीं",
    },
    answer: "A",
  },
  {
    id: 8,
    question: "यदि cos θ = 0.6 है, तो sin θ का मान क्या होगा?",
    options: {
      A: "0.4",
      B: "0.8",
      C: "0.5",
      D: "0.3",
    },
    answer: "B",
  },
  {
    id: 9,
    question: "sec 90° का मान क्या होता है?",
    options: {
      A: "0",
      B: "1",
      C: "अनंत",
      D: "√2",
    },
    answer: "C",
  },
  {
    id: 10,
    question: "cot 0° का मान क्या होता है?",
    options: {
      A: "0",
      B: "अनंत",
      C: "1",
      D: "1/√3",
    },
    answer: "B",
  },
  {
    id: 11,
    question: "sin 90° का मान क्या है?",
    options: {
      A: "0",
      B: "1",
      C: "-1",
      D: "1/2",
    },
    answer: "B",
  },
  {
    id: 12,
    question: "यदि sin θ = 4/5 हो, तो cos θ का मान क्या होगा?",
    options: {
      A: "3/5",
      B: "1/5",
      C: "√3/2",
      D: "4/5",
    },
    answer: "A",
  },
  {
    id: 13,
    question: "tan 60° का मान क्या है?",
    options: {
      A: "1/√3",
      B: "1",
      C: "√3",
      D: "2",
    },
    answer: "C",
  },
  {
    id: 14,
    question: "cos 30° का मान क्या होता है?",
    options: {
      A: "1/2",
      B: "√3/2",
      C: "0",
      D: "1",
    },
    answer: "B",
  },
  {
    id: 15,
    question: "यदि θ = 45° है, तो sin θ और cos θ के मान क्या होंगे?",
    options: {
      A: "1 और 0",
      B: "1 और 1",
      C: "1/√2 और 1/√2",
      D: "√3/2 और 1/2",
    },
    answer: "C",
  },
  {
    id: 16,
    question: "cosec 90° का मान क्या होता है?",
    options: {
      A: "1",
      B: "2",
      C: "0",
      D: "अनंत",
    },
    answer: "A",
  },
  {
    id: 17,
    question: "sec 45° का मान क्या है?",
    options: {
      A: "1/√2",
      B: "√2",
      C: "1",
      D: "2",
    },
    answer: "B",
  },
  {
    id: 18,
    question: "यदि cot θ = 1 हो, तो θ का मान क्या होगा?",
    options: {
      A: "30°",
      B: "60°",
      C: "45°",
      D: "90°",
    },
    answer: "C",
  },
  {
    id: 19,
    question: "tan θ का मान कब अनंत होगा?",
    options: {
      A: "θ = 45°",
      B: "θ = 90°",
      C: "θ = 0°",
      D: "θ = 60°",
    },
    answer: "B",
  },
  {
    id: 20,
    question: "यदि sec θ = 2, तो cos θ का मान क्या होगा?",
    options: {
      A: "1/2",
      B: "2",
      C: "0",
      D: "√2",
    },
    answer: "A",
  },
];
